### ISSUE TITLE
Images are upside down

### ISSUE THREAD

**Issue by paulthomson** [paulthomson/get-image#1]
I think images are upside down when compared to glsl sandbox. I did try to understand why a while ago but I couldn't really see the issue! I thought maybe one of the triangles should have been drawn clockwise, not counter-clockwise (or vice versa), but that doesn't make sense since the image looks correct (apart from being upside down)!

**Comment by 0152la** [comment]
Fixed in aea280c4e6554c34145927965a720a0644cabb43.
